### ISSUE TITLE
Command contains * not working

### ISSUE THREAD

**Issue by pingyu0720** [magiclen/MagicCommand#1]
Command command = new Command("ls *");
	command.setCommandListener(new CommandListener() {
		public void commandStart(String arg0) {
					
		}
		public void commandRunning(String arg0, String arg1, boolean arg2) {
			System.out.println("commandRunning = " + arg1 );
		}
		public void commandException(String arg0, Exception arg1) {
					
		}
		public void commandEnd(String arg0, int arg1) {
					
		}
	});
	command.run();

I get this error:

	ls: *: No such file or directory

**Comment by magiclen** [comment]
Try `bash -c` to interpret the wildcard

```java
Command command = new Command("bash -c ls *");
```
